<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Mirchi</RootNamespace>
    <AssemblyName>Mirchi</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
